"""create exercise catalog tables

Revision ID: aac1928a382a
Revises: 58ad1d593a3b
Create Date: 2026-08-21 17:11:21.747143

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aac1928a382a"
down_revision: str | Sequence[str] | None = "58ad1d593a3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
muscle_groups_table = sa.table(
    "muscle_groups",
    sa.column("code", sa.String()),
    sa.column("names", sa.JSON()),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muscle_groups",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column(
            "names",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_muscle_groups")),
    )
    op.bulk_insert(
        muscle_groups_table,
        [
            {"code": "chest", "names": {"en": "Chest", "uk": "Груди"}},
            {"code": "back", "names": {"en": "Back", "uk": "Спина"}},
            {
                "code": "shoulders",
                "names": {"en": "Shoulders", "uk": "Плечі"},
            },
            {"code": "biceps", "names": {"en": "Biceps", "uk": "Біцепс"}},
            {"code": "triceps", "names": {"en": "Triceps", "uk": "Трицепс"}},
            {
                "code": "core",
                "names": {"en": "Core", "uk": "М’язи кора"},
            },
            {
                "code": "glutes",
                "names": {"en": "Glutes", "uk": "Сідничні м’язи"},
            },
            {
                "code": "quadriceps",
                "names": {"en": "Quadriceps", "uk": "Квадрицепс"},
            },
            {
                "code": "hamstrings",
                "names": {
                    "en": "Hamstrings",
                    "uk": "Задня поверхня стегна",
                },
            },
            {
                "code": "calves",
                "names": {"en": "Calves", "uk": "Литкові м’язи"},
            },
        ],
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=80), nullable=True),
        sa.Column(
            "names",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(owner_user_id IS NULL AND code IS NOT NULL) OR (owner_user_id IS NOT NULL AND code is NULL)",
            name="ownership_matches_code",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_exercises_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
        sa.UniqueConstraint("code", name=op.f("uq_exercises_code")),
    )
    op.create_index(
        op.f("ix_exercises_owner_user_id"), "exercises", ["owner_user_id"], unique=False
    )
    op.create_table(
        "exercise_muscle_groups",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("muscle_group_code", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_muscle_groups_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["muscle_group_code"],
            ["muscle_groups.code"],
            name=op.f("fk_exercise_muscle_groups_muscle_group_code_muscle_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "exercise_id", "muscle_group_code", name=op.f("pk_exercise_muscle_groups")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exercise_muscle_groups")
    op.drop_index(op.f("ix_exercises_owner_user_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_table("muscle_groups")
    # ### end Alembic commands ###
