"""create workout session tables

Revision ID: abf6a00427c1
Revises: f4d29b30f598
Create Date: 2026-09-16 19:49:30.196602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "abf6a00427c1"
down_revision: str | Sequence[str] | None = "f4d29b30f598"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'completed' AND completed_at IS NOT NULL) OR (status IN ('in_progress', 'cancelled') AND completed_at IS NULL)",
            name="completion_time_matches_status",
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'cancelled')", name="status_allowed"
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name="completion_not_before_start",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["workout_templates.id"],
            name=op.f("fk_workout_sessions_template_id_workout_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workout_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sessions")),
    )
    op.create_index(
        op.f("ix_workout_sessions_template_id"),
        "workout_sessions",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workout_sessions_user_id"),
        "workout_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_workout_sessions_user_in_progress",
        "workout_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
        sqlite_where=sa.text("status = 'in_progress'"),
    )
    op.create_table(
        "workout_session_exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "exercise_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("position >= 0", name="position_non_negative"),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_workout_session_exercises_exercise_id_exercises"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_sessions.id"],
            name=op.f("fk_workout_session_exercises_session_id_workout_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_session_exercises")),
        sa.UniqueConstraint(
            "session_id",
            "position",
            name="uq_workout_session_exercises_session_position",
        ),
    )
    op.create_index(
        op.f("ix_workout_session_exercises_exercise_id"),
        "workout_session_exercises",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workout_session_exercises_session_id"),
        "workout_session_exercises",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "workout_session_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_type", sa.String(length=20), nullable=False),
        sa.Column("planned_reps", sa.Integer(), nullable=True),
        sa.Column("planned_weight_kg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("actual_reps", sa.Integer(), nullable=True),
        sa.Column("actual_weight_kg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'completed' AND actual_reps IS NOT NULL AND completed_at IS NOT NULL) OR (status IN ('pending', 'skipped') AND completed_at IS NULL)",
            name="completion_fields_match_status",
        ),
        sa.CheckConstraint(
            "set_type IN ('warmup', 'working')", name="set_type_allowed"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'skipped')", name="status_allowed"
        ),
        sa.CheckConstraint(
            "actual_reps IS NULL OR actual_reps > 0", name="actual_reps_positive"
        ),
        sa.CheckConstraint(
            "actual_weight_kg IS NULL OR actual_weight_kg >= 0",
            name="actual_weight_non_negative",
        ),
        sa.CheckConstraint(
            "planned_reps IS NULL OR planned_reps > 0", name="planned_reps_positive"
        ),
        sa.CheckConstraint(
            "planned_weight_kg IS NULL OR planned_weight_kg >= 0",
            name="planned_weight_non_negative",
        ),
        sa.CheckConstraint("position >= 0", name="position_non_negative"),
        sa.ForeignKeyConstraint(
            ["session_exercise_id"],
            ["workout_session_exercises.id"],
            name=op.f(
                "fk_workout_session_sets_session_exercise_id_workout_session_exercises"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_session_sets")),
        sa.UniqueConstraint(
            "session_exercise_id",
            "position",
            name="uq_workout_session_sets_exercise_position",
        ),
    )
    op.create_index(
        op.f("ix_workout_session_sets_session_exercise_id"),
        "workout_session_sets",
        ["session_exercise_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workout_session_sets_session_exercise_id"),
        table_name="workout_session_sets",
    )
    op.drop_table("workout_session_sets")
    op.drop_index(
        op.f("ix_workout_session_exercises_session_id"),
        table_name="workout_session_exercises",
    )
    op.drop_index(
        op.f("ix_workout_session_exercises_exercise_id"),
        table_name="workout_session_exercises",
    )
    op.drop_table("workout_session_exercises")
    op.drop_index(
        "uq_workout_sessions_user_in_progress",
        table_name="workout_sessions",
        postgresql_where=sa.text("status = 'in_progress'"),
        sqlite_where=sa.text("status = 'in_progress'"),
    )
    op.drop_index(op.f("ix_workout_sessions_user_id"), table_name="workout_sessions")
    op.drop_index(
        op.f("ix_workout_sessions_template_id"), table_name="workout_sessions"
    )
    op.drop_table("workout_sessions")
    # ### end Alembic commands ###
