"""create workout template tables

Revision ID: f4d29b30f598
Revises: aac1928a382a
Create Date: 2026-08-25 19:11:28.995006

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4d29b30f598"
down_revision: str | Sequence[str] | None = "aac1928a382a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workout_templates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_templates")),
    )
    op.create_index(
        op.f("ix_workout_templates_user_id"),
        "workout_templates",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "workout_template_exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("position >= 0", name="position_non_negative"),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_workout_template_exercises_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["workout_templates.id"],
            name=op.f("fk_workout_template_exercises_template_id_workout_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_template_exercises")),
        sa.UniqueConstraint(
            "template_id",
            "position",
            name="uq_workout_template_exercises_template_position",
        ),
    )
    op.create_index(
        op.f("ix_workout_template_exercises_exercise_id"),
        "workout_template_exercises",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workout_template_exercises_template_id"),
        "workout_template_exercises",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "workout_template_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_type", sa.String(length=20), nullable=False),
        sa.Column("target_reps", sa.Integer(), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.CheckConstraint(
            "set_type IN ('warmup', 'working')", name="set_type_allowed"
        ),
        sa.CheckConstraint("position >= 0", name="position_non_negative"),
        sa.CheckConstraint("target_reps > 0", name="target_reps_positive"),
        sa.CheckConstraint(
            "target_weight_kg IS NULL OR target_weight_kg >= 0",
            name="target_weight_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["template_exercise_id"],
            ["workout_template_exercises.id"],
            name=op.f(
                "fk_workout_template_sets_template_exercise_id_workout_template_exercises"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_template_sets")),
        sa.UniqueConstraint(
            "template_exercise_id",
            "position",
            name="uq_workout_template_sets_exercise_position",
        ),
    )
    op.create_index(
        op.f("ix_workout_template_sets_template_exercise_id"),
        "workout_template_sets",
        ["template_exercise_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workout_template_sets_template_exercise_id"),
        table_name="workout_template_sets",
    )
    op.drop_table("workout_template_sets")
    op.drop_index(
        op.f("ix_workout_template_exercises_template_id"),
        table_name="workout_template_exercises",
    )
    op.drop_index(
        op.f("ix_workout_template_exercises_exercise_id"),
        table_name="workout_template_exercises",
    )
    op.drop_table("workout_template_exercises")
    op.drop_index(op.f("ix_workout_templates_user_id"), table_name="workout_templates")
    op.drop_table("workout_templates")
    # ### end Alembic commands ###
